export enum ProfilEnum {
  PROMOTEUR = 'PROMOTEUR',
  NOTAIRE = 'NOTAIRE',
  ADMIN = 'ADMIN',
  RESERVATAIRE = 'RESERVATAIRE',
  AGENCY = 'AGENCY',
  BANK = 'BANK',
  SYNDIC = 'SYNDIC',
  PROPRIETAIRE = 'PROPRIETAIRE',
  TENANT = 'TENANT',
  COPROPRIETAIRE = 'COPROPRIETAIRE',
}
